

networks:
  dikreis:
    name: dikreis
    driver: bridge

services:
  nginx:
    container_name: nginx-new
    build: ./nginx-new
    image: nginx-new
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - dikreis

  wordpress:
    container_name: wordpress-new
    build: ./wordpress-new
    image: wordpress-new
    depends_on:
      - mariadb
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - dikreis

  mariadb:
    container_name: mariadb-new
    build: ./mariadb-new
    image: mariadb-new
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - dikreis

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dkreise/data/wordpress
      o: bind

  database:
    driver: local
    driver_opts:
      type: none
      device: /home/dkreise/data/mysql
      o: bind
